# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  ports:
  - port: 80
    targetPort: 1234
    protocol: TCP
  selector:
    app: go-app
  type: ClusterIP
